import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:subscription_tracker/presentation/providers/app_providers.dart';

/// Simple app-level translations
class AppLocalizations {
  final String language;
  String get localeCode => switch (language) {
        'Türkçe' => 'tr',
        'Español' => 'es',
        'Français' => 'fr',
        'Deutsch' => 'de',
        _ => 'en',
      };

  AppLocalizations(this.language);

  static final Map<String, Map<String, String>> _translations = {
    'English': {
      'settings': 'Settings',
      'preferences': 'Preferences',
      'default_currency': 'Default Currency',
      'theme': 'Theme',
      'language': 'Language',
      'notifications': 'Notifications',
      'notifications_subtitle': 'Get notified before payment dates',
      'reminder_days': 'Reminder Days Before',
      'security_data': 'Security & Data',
      'biometric_lock': 'Biometric Lock',
      'biometric_subtitle': 'Require biometric to open the app',
      'export_data': 'Export Data',
      'import_data': 'Import Data',
      'about': 'About',
      'version': 'Version',
      'rate_app': 'Rate App',
      'privacy_policy': 'Privacy Policy',
      'my_subscriptions': 'My Subscriptions',
      'monthly_total': 'Monthly Total',
      'upcoming': 'Upcoming',
      'all_subscriptions': 'All Subscriptions',
      'no_upcoming': 'No upcoming payments',
      'no_subscriptions': 'No subscriptions yet',
      'days': 'days',
      'in_days': 'in {0} days',
      'add_subscription': 'Add Subscription',
      'templates': 'Templates',
      'manual': 'Manual',
      'search_templates': 'Search templates...',
      'name': 'Name',
      'amount': 'Amount',
      'start_date': 'Start Date',
      'save_subscription': 'Save Subscription',
      'cant_find': "Can't find? Add manually",
      'select_theme': 'Select Theme',
      'select_currency': 'Select Currency',
      'select_language': 'Select Language',
      'remind_me_before': 'Remind Me Before',
      'day_before': '{0} day before',
      'days_before': '{0} days before',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'delete_subscription': 'Delete Subscription',
      'delete_confirm': 'Are you sure you want to delete "{0}"?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'deleted': '{0} deleted',
      'error_deleting': 'Error deleting: {0}',
      'notifications_enabled': 'Notifications enabled',
      'notifications_disabled': 'Notifications disabled',
      'biometric_enabled': 'Biometric lock enabled',
      'biometric_disabled': 'Biometric lock disabled',
      'export_coming_soon': 'Export feature coming soon',
      'import_coming_soon': 'Import feature coming soon',
      'thank_you': 'Thank you for your support!',
      'privacy_browser': 'Privacy policy will open in browser',
      'dashboard': 'Dashboard',
      'subscriptions': 'Subscriptions',
      'analytics': 'Analytics',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'total_spent': 'Total Spent',
      'spending_by_category': 'Spending by Category',
      'monthly_trend': 'Monthly Trend',
      'not_found': 'Subscription not found',
      'search_subscriptions': 'Search subscriptions...',
      'next': 'Next',
      'today': 'Today',
    },
    'Türkçe': {
      'settings': 'Ayarlar',
      'preferences': 'Tercihler',
      'default_currency': 'Varsayılan Para Birimi',
      'theme': 'Tema',
      'language': 'Dil',
      'notifications': 'Bildirimler',
      'notifications_subtitle': 'Ödeme tarihlerinden önce bildirim al',
      'reminder_days': 'Hatırlatma Gün Sayısı',
      'security_data': 'Güvenlik ve Veri',
      'biometric_lock': 'Biyometrik Kilit',
      'biometric_subtitle': 'Uygulamayı açmak için biyometrik zorunlu olsun',
      'export_data': 'Verileri Dışa Aktar',
      'import_data': 'Verileri İçe Aktar',
      'about': 'Hakkında',
      'version': 'Sürüm',
      'rate_app': 'Uygulamayı Değerlendir',
      'privacy_policy': 'Gizlilik Politikası',
      'my_subscriptions': 'Aboneliklerim',
      'monthly_total': 'Aylık Toplam',
      'upcoming': 'Yaklaşan',
      'all_subscriptions': 'Tüm Abonelikler',
      'no_upcoming': 'Yaklaşan ödeme yok',
      'no_subscriptions': 'Henüz abonelik yok',
      'days': 'gün',
      'in_days': '{0} gün içinde',
      'add_subscription': 'Abonelik Ekle',
      'templates': 'Şablonlar',
      'manual': 'Manuel',
      'search_templates': 'Şablon ara...',
      'name': 'İsim',
      'amount': 'Tutar',
      'start_date': 'Başlangıç Tarihi',
      'save_subscription': 'Aboneliği Kaydet',
      'cant_find': 'Bulamadınız mı? Manuel ekleyin',
      'select_theme': 'Tema Seçin',
      'select_currency': 'Para Birimi Seçin',
      'select_language': 'Dil Seçin',
      'remind_me_before': 'Hatırlatma Zamanı',
      'day_before': '{0} gün önce',
      'days_before': '{0} gün önce',
      'light': 'Açık',
      'dark': 'Koyu',
      'system': 'Sistem',
      'delete_subscription': 'Aboneliği Sil',
      'delete_confirm': '"{0}" silinsin mi?',
      'cancel': 'İptal',
      'delete': 'Sil',
      'deleted': '{0} silindi',
      'error_deleting': 'Silme hatası: {0}',
      'notifications_enabled': 'Bildirimler açıldı',
      'notifications_disabled': 'Bildirimler kapatıldı',
      'biometric_enabled': 'Biyometrik kilit açıldı',
      'biometric_disabled': 'Biyometrik kilit kapatıldı',
      'export_coming_soon': 'Dışa aktarma yakında gelecek',
      'import_coming_soon': 'İçe aktarma yakında gelecek',
      'thank_you': 'Desteğiniz için teşekkürler!',
      'privacy_browser': 'Gizlilik politikası tarayıcıda açılacak',
      'dashboard': 'Ana Sayfa',
      'subscriptions': 'Abonelikler',
      'analytics': 'Analiz',
      'weekly': 'Haftalık',
      'monthly': 'Aylık',
      'yearly': 'Yıllık',
      'total_spent': 'Toplam Harcama',
      'spending_by_category': 'Kategoriye Göre Harcama',
      'monthly_trend': 'Aylık Trend',
      'not_found': 'Abonelik bulunamadı',
      'search_subscriptions': 'Aboneliklerde ara...',
      'next': 'Sonraki',
      'today': 'Bugün',
    },
    'Español': {
      'settings': 'Configuración',
      'preferences': 'Preferencias',
      'default_currency': 'Moneda Predeterminada',
      'theme': 'Tema',
      'language': 'Idioma',
      'notifications': 'Notificaciones',
      'notifications_subtitle': 'Recibir notificaciones antes de las fechas de pago',
      'reminder_days': 'Días de Recordatorio',
      'security_data': 'Seguridad y Datos',
      'biometric_lock': 'Bloqueo Biométrico',
      'biometric_subtitle': 'Requerir biometría para abrir la app',
      'export_data': 'Exportar Datos',
      'import_data': 'Importar Datos',
      'about': 'Acerca de',
      'version': 'Versión',
      'rate_app': 'Calificar App',
      'privacy_policy': 'Política de Privacidad',
      'my_subscriptions': 'Mis Suscripciones',
      'monthly_total': 'Total Mensual',
      'upcoming': 'Próximos',
      'all_subscriptions': 'Todas las Suscripciones',
      'no_upcoming': 'No hay pagos próximos',
      'no_subscriptions': 'Aún no hay suscripciones',
      'days': 'días',
      'in_days': 'en {0} días',
      'add_subscription': 'Agregar Suscripción',
      'templates': 'Plantillas',
      'manual': 'Manual',
      'search_templates': 'Buscar plantillas...',
      'name': 'Nombre',
      'amount': 'Monto',
      'start_date': 'Fecha de Inicio',
      'save_subscription': 'Guardar Suscripción',
      'cant_find': '¿No lo encuentras? Agregar manualmente',
      'select_theme': 'Seleccionar Tema',
      'select_currency': 'Seleccionar Moneda',
      'select_language': 'Seleccionar Idioma',
      'remind_me_before': 'Recordarme Antes',
      'day_before': '{0} día antes',
      'days_before': '{0} días antes',
      'light': 'Claro',
      'dark': 'Oscuro',
      'system': 'Sistema',
      'delete_subscription': 'Eliminar Suscripción',
      'delete_confirm': '¿Estás seguro de eliminar "{0}"?',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'deleted': '{0} eliminado',
      'error_deleting': 'Error al eliminar: {0}',
      'notifications_enabled': 'Notificaciones activadas',
      'notifications_disabled': 'Notificaciones desactivadas',
      'biometric_enabled': 'Bloqueo biométrico activado',
      'biometric_disabled': 'Bloqueo biométrico desactivado',
      'export_coming_soon': 'Exportación disponible pronto',
      'import_coming_soon': 'Importación disponible pronto',
      'thank_you': '¡Gracias por tu apoyo!',
      'privacy_browser': 'La política de privacidad se abrirá en el navegador',
      'dashboard': 'Panel',
      'subscriptions': 'Suscripciones',
      'analytics': 'Analítica',
      'weekly': 'Semanal',
      'monthly': 'Mensual',
      'yearly': 'Anual',
      'total_spent': 'Total Gastado',
      'spending_by_category': 'Gasto por Categoría',
      'monthly_trend': 'Tendencia Mensual',
      'not_found': 'Suscripción no encontrada',
      'search_subscriptions': 'Buscar suscripciones...',
      'next': 'Próximo',
      'today': 'Hoy',
    },
    'Français': {
      'settings': 'Paramètres',
      'preferences': 'Préférences',
      'default_currency': 'Devise par Défaut',
      'theme': 'Thème',
      'language': 'Langue',
      'notifications': 'Notifications',
      'notifications_subtitle': 'Recevoir des notifications avant les dates de paiement',
      'reminder_days': 'Jours de Rappel',
      'security_data': 'Sécurité et Données',
      'biometric_lock': 'Verrou Biométrique',
      'biometric_subtitle': "Exiger la biométrie pour ouvrir l'app",
      'export_data': 'Exporter les Données',
      'import_data': 'Importer les Données',
      'about': 'À Propos',
      'version': 'Version',
      'rate_app': "Noter l'App",
      'privacy_policy': 'Politique de Confidentialité',
      'my_subscriptions': 'Mes Abonnements',
      'monthly_total': 'Total Mensuel',
      'upcoming': 'À Venir',
      'all_subscriptions': 'Tous les Abonnements',
      'no_upcoming': 'Aucun paiement à venir',
      'no_subscriptions': "Pas encore d'abonnements",
      'days': 'jours',
      'in_days': 'dans {0} jours',
      'add_subscription': 'Ajouter un Abonnement',
      'templates': 'Modèles',
      'manual': 'Manuel',
      'search_templates': 'Rechercher des modèles...',
      'name': 'Nom',
      'amount': 'Montant',
      'start_date': 'Date de Début',
      'save_subscription': "Enregistrer l'Abonnement",
      'cant_find': 'Introuvable ? Ajouter manuellement',
      'select_theme': 'Sélectionner le Thème',
      'select_currency': 'Sélectionner la Devise',
      'select_language': 'Sélectionner la Langue',
      'remind_me_before': 'Me Rappeler Avant',
      'day_before': '{0} jour avant',
      'days_before': '{0} jours avant',
      'light': 'Clair',
      'dark': 'Sombre',
      'system': 'Système',
      'delete_subscription': "Supprimer l'Abonnement",
      'delete_confirm': 'Êtes-vous sûr de vouloir supprimer "{0}" ?',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'deleted': '{0} supprimé',
      'error_deleting': 'Erreur de suppression : {0}',
      'notifications_enabled': 'Notifications activées',
      'notifications_disabled': 'Notifications désactivées',
      'biometric_enabled': 'Verrou biométrique activé',
      'biometric_disabled': 'Verrou biométrique désactivé',
      'export_coming_soon': 'Exportation bientôt disponible',
      'import_coming_soon': 'Importation bientôt disponible',
      'thank_you': 'Merci pour votre soutien !',
      'privacy_browser': 'La politique de confidentialité ouvrira dans le navigateur',
      'dashboard': 'Tableau de Bord',
      'subscriptions': 'Abonnements',
      'analytics': 'Analytique',
      'weekly': 'Hebdomadaire',
      'monthly': 'Mensuel',
      'yearly': 'Annuel',
      'total_spent': 'Total Dépensé',
      'spending_by_category': 'Dépenses par Catégorie',
      'monthly_trend': 'Tendance Mensuelle',
      'not_found': 'Abonnement introuvable',
      'search_subscriptions': 'Rechercher des abonnements...',
      'next': 'Suivant',
      'today': "Aujourd'hui",
    },
    'Deutsch': {
      'settings': 'Einstellungen',
      'preferences': 'Voreinstellungen',
      'default_currency': 'Standardwährung',
      'theme': 'Design',
      'language': 'Sprache',
      'notifications': 'Benachrichtigungen',
      'notifications_subtitle': 'Vor Zahlungsterminen benachrichtigt werden',
      'reminder_days': 'Erinnerung Tage vorher',
      'security_data': 'Sicherheit & Daten',
      'biometric_lock': 'Biometrische Sperre',
      'biometric_subtitle': 'Biometrie zum Öffnen erforderlich',
      'export_data': 'Daten Exportieren',
      'import_data': 'Daten Importieren',
      'about': 'Über',
      'version': 'Version',
      'rate_app': 'App Bewerten',
      'privacy_policy': 'Datenschutzrichtlinie',
      'my_subscriptions': 'Meine Abonnements',
      'monthly_total': 'Monatliche Summe',
      'upcoming': 'Bevorstehend',
      'all_subscriptions': 'Alle Abonnements',
      'no_upcoming': 'Keine bevorstehenden Zahlungen',
      'no_subscriptions': 'Noch keine Abonnements',
      'days': 'Tage',
      'in_days': 'in {0} Tagen',
      'add_subscription': 'Abonnement Hinzufügen',
      'templates': 'Vorlagen',
      'manual': 'Manuell',
      'search_templates': 'Vorlagen suchen...',
      'name': 'Name',
      'amount': 'Betrag',
      'start_date': 'Startdatum',
      'save_subscription': 'Abonnement Speichern',
      'cant_find': 'Nicht gefunden? Manuell hinzufügen',
      'select_theme': 'Design Auswählen',
      'select_currency': 'Währung Auswählen',
      'select_language': 'Sprache Auswählen',
      'remind_me_before': 'Erinnere Mich Vorher',
      'day_before': '{0} Tag vorher',
      'days_before': '{0} Tage vorher',
      'light': 'Hell',
      'dark': 'Dunkel',
      'system': 'System',
      'delete_subscription': 'Abonnement Löschen',
      'delete_confirm': 'Möchten Sie "{0}" wirklich löschen?',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'deleted': '{0} gelöscht',
      'error_deleting': 'Fehler beim Löschen: {0}',
      'notifications_enabled': 'Benachrichtigungen aktiviert',
      'notifications_disabled': 'Benachrichtigungen deaktiviert',
      'biometric_enabled': 'Biometrische Sperre aktiviert',
      'biometric_disabled': 'Biometrische Sperre deaktiviert',
      'export_coming_soon': 'Export kommt bald',
      'import_coming_soon': 'Import kommt bald',
      'thank_you': 'Danke für Ihre Unterstützung!',
      'privacy_browser': 'Datenschutzrichtlinie wird im Browser geöffnet',
      'dashboard': 'Dashboard',
      'subscriptions': 'Abonnements',
      'analytics': 'Analytik',
      'weekly': 'Wöchentlich',
      'monthly': 'Monatlich',
      'yearly': 'Jährlich',
      'total_spent': 'Gesamtausgaben',
      'spending_by_category': 'Ausgaben nach Kategorie',
      'monthly_trend': 'Monatstrend',
      'not_found': 'Abonnement nicht gefunden',
      'search_subscriptions': 'Abonnements suchen...',
      'next': 'Nächste',
      'today': 'Heute',
    },
  };

  String tr(String key) {
    return _translations[language]?[key] ?? _translations['English']?[key] ?? key;
  }

  /// Translate with placeholder replacement: {0}, {1}, etc.
  String trArgs(String key, List<String> args) {
    var text = tr(key);
    for (var i = 0; i < args.length; i++) {
      text = text.replaceAll('{$i}', args[i]);
    }
    return text;
  }
}

/// Provider that gives the current AppLocalizations based on selected language
final appLocalizationsProvider = Provider<AppLocalizations>((ref) {
  final language = ref.watch(selectedLanguageProvider);
  return AppLocalizations(language);
});
